// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJVPFBo6BgzLFGtLQ3YSY_37zFbf0JOo4',
    appId: '1:310622873925:web:5547405b5c9f656063f62c',
    messagingSenderId: '310622873925',
    projectId: 'dorm-link',
    authDomain: 'dorm-link.firebaseapp.com',
    storageBucket: 'dorm-link.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5L8rPmtQn_A4oaj5j43ERkrzCJ4U-aQw',
    appId: '1:310622873925:android:3e72b2cf2929a05a63f62c',
    messagingSenderId: '310622873925',
    projectId: 'dorm-link',
    storageBucket: 'dorm-link.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMSHG4norbBf7k5f5rMnS5jcsd6XHBAK8',
    appId: '1:310622873925:ios:173a280b4da58a8563f62c',
    messagingSenderId: '310622873925',
    projectId: 'dorm-link',
    storageBucket: 'dorm-link.appspot.com',
    iosClientId: '310622873925-4648ga96in7f1tm7rc1per50u8d9e4ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.dormLink',
  );
}
